/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_i_uf_Main_Person */

#ifndef _Included_com_i_uf_Main_Person
#define _Included_com_i_uf_Main_Person
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_i_uf_Main_Person
 * Method:    getID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_i_1uf_Main_00024Person_getID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
