/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_i_uf_Main */

#ifndef _Included_com_i_uf_Main
#define _Included_com_i_uf_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_i_uf_Main
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_i_1uf_Main_helloWorld
  (JNIEnv *, jclass);

/*
 * Class:     com_i_uf_Main
 * Method:    second
 * Signature: (Lcom/i_uf/Main/Person;)Lcom/i_uf/Main/Person;
 */
JNIEXPORT jobject JNICALL Java_com_i_1uf_Main_second
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_i_uf_Main
 * Method:    fourth
 * Signature: (Lcom/i_uf/Main/Person;)Lcom/i_uf/Main/Person;
 */
JNIEXPORT jobject JNICALL Java_com_i_1uf_Main_fourth
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
